controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# On peut gérer les routes ici
# home:
#    path: /
#    controller: App\Controller\HomeController::index
